###
POST http://localhost:3820/api/gavs/com.example/application/1.0
Content-Type: application/json

[
  "com.example:application:1.0",
  "com.example:clients:1.0",
  "com.example:dtos:1.0",
  "com.example:utils:0.1"
]

###
POST http://localhost:3820/api/gavs/com.example/clients/1.0
Content-Type: application/json

[
  "com.example:dtos:1.0",
  "com.example:utils:0.1"
]

###
GET http://localhost:3820/api/gavs/com.example/application/1.0

###
GET http://localhost:3820/api/gavs/com.example/application/1.0/dependencies

###
GET http://localhost:3820/api/gavs/com.example/utils/0.1

###
GET http://localhost:3820/api/gavs/com.example/utils/0.1/dependents
